//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoseItSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public int Id { get; set; }
        public bool IsMatchAdmin { get; set; }
        public int MatchId { get; set; }
        public string ApplicationUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Match Match { get; set; }
    }
}
